import './App.css';

export const books2024 = [
	{
		id: 1,
		title: 'Development and Integration in Latin America: An Odyssey Unfinished',
		year: 2023,
		editorial: 'North American Business Press, Inc.',
		price: '35,00 $',
		source: 'https://www.amazon.com/-/es/Armando-Filippo/dp/1948915308/ref=sr_1_1?__mk_es_US=ÅMÅŽÕÑ&crid=RUKNQMIPRHX7&dib=eyJ2IjoiMSJ9.p9dEdey6Vzj_aqJhmtsbNkirSqdnDYm8m2sL2CY-xHYWN9MlRLUbEc3bZp1e5C0TaFPm0NfWpirxlT-y4RjYu_FfMExVJQp8TeNdAswniFvcceLfJ9jYLQX_qPMGbvt1cLdHP6647dHZFBq_HOpvw5W9B_FLV5H95NNxsjTh4l0EphX4saFm2kFhHkT45H_W_CEGaWeA_HG5eRpik14HR39DH2Qo81TdPflA_1nLo40.Okdo03LEtPY7AcT5GaIkmoyk0p8Uc8XKpIy_6GXhoYc&dib_tag=se&keywords=armando+di+filippo&qid=1708529341&sprefix=armando+di+fil%2Caps%2C434&sr=8-1',
		description: 'This book considers Latin American structuralism (L.A.S) as a school of thought that was proposed to explain the foundations of the development of Latin America starting from its colonial and peripheral origins. L.A.S cultivated a Latin Americanism based on the idea of liberation against the structures of domination and dependence that, since the colonial phase, fragmented the region to submit it to the interests of successive hegemonic centers. The first part of this book presents a counterpoint between the notions of capitalism and development. The second part recounts the influence of the founding fathers of L.A.S who, based on the formidable impetus of the United Nations (ECLAC), characterized the essential features of Latin American structuralism. The third part deepens the study of these features and the ideal of Latin American unity. The fourth and last part deals with the issue of political power under a republican and multidimensional conception of democracy. The author especially emphasizes the validity of the philosophy of history proposed by L.A.S not only for the study of Latin American societies but also for an adequate interpretation of the impact of the technical change generated by the current cybernetic capitalism that is transforming the world at an unprecedented scale and speed.',
		state: 'NUEVO',
		topic: 'Economía y Desarrollo Económico',
		language: 'Inglés',
		source2: undefined
	},
	{
		id: 2,
		title: 'Poder, capitalismo y democracia',
		year: 2013,
		editorial: 'RIL Editores',
		price: '14,99 $',
		source: 'https://www.amazon.com/-/es/Armando-Filippo-ebook/dp/B00HX2P5PI/ref=sr_1_4?__mk_es_US=ÅMÅŽÕÑ&crid=RUKNQMIPRHX7&dib=eyJ2IjoiMSJ9.p9dEdey6Vzj_aqJhmtsbNkirSqdnDYm8m2sL2CY-xHYWN9MlRLUbEc3bZp1e5C0TaFPm0NfWpirxlT-y4RjYu_FfMExVJQp8TeNdAswniFvcceLfJ9jYLQX_qPMGbvt1cLdHP6647dHZFBq_HOpvw5W9B_FLV5H95NNxsjTh4l0EphX4saFm2kFhHkT45H_W_CEGaWeA_HG5eRpik14HR39DH2Qo81TdPflA_1nLo40.Okdo03LEtPY7AcT5GaIkmoyk0p8Uc8XKpIy_6GXhoYc&dib_tag=se&keywords=armando+di+filippo&qid=1708529341&sprefix=armando+di+fil%2Caps%2C434&sr=8-4',
		description: 'Este libro se propone examinar los vínculos entre el capitalismo y la democracia en el marco de la globalización de las sociedades humanas del tercer milenio. Expresa la mirada de un economista formado en una visión sistémica, multidimensional y dinámica de las ciencias sociales. Los cambios histórico-estructurales interrelacionados del capitalismo y la democracia pueden encuadrarse fructíferamente en dicha visión epistemológica.\n' +
			'La crítica del capitalismo es el foco central de la argumentación. El capitalismo es entendido como un sistema de poder y dominación que ha estructurado la vida económica y modelado la cultura de las sociedades occidentales desde hace al menos doscientos años.\n' +
			'El sistema político es la principal fuente alternativa de poder societal capaz de encausar el lucro y ponerlo al servicio de fines humanos socialmente legitimables. Pero el sistema político no puede anular o subrogar las formas económicas del poder.',
		state: null,
		topic: 'Filosofía política y económica',
		language: 'Español',
		source2: 'https://rileditores.com/tienda/poder-capitalismo-y-democracia/'
	},
	{
		id: 3,
		title: 'El desarrollo y la integración de América Latina: Una odisea inconclusa',
		year: 2021,
		editorial: 'Ediciones Universidad Alberto Hurtado',
		price: '8,99 $',
		source: 'https://www.amazon.com/-/es/Armando-Filippo-ebook/dp/B09HN6YMN5/ref=sr_1_3?__mk_es_US=ÅMÅŽÕÑ&crid=RUKNQMIPRHX7&dib=eyJ2IjoiMSJ9.p9dEdey6Vzj_aqJhmtsbNkirSqdnDYm8m2sL2CY-xHYWN9MlRLUbEc3bZp1e5C0TaFPm0NfWpirxlT-y4RjYu_FfMExVJQp8TeNdAswniFvcceLfJ9jYLQX_qPMGbvt1cLdHP6647dHZFBq_HOpvw5W9B_FLV5H95NNxsjTh4l0EphX4saFm2kFhHkT45H_W_CEGaWeA_HG5eRpik14HR39DH2Qo81TdPflA_1nLo40.Okdo03LEtPY7AcT5GaIkmoyk0p8Uc8XKpIy_6GXhoYc&dib_tag=se&keywords=armando+di+filippo&qid=1708529341&sprefix=armando+di+fil%2Caps%2C434&sr=8-3',
		description: 'Este libro narra la epopeya inconclusa de las naciones latinoamericanas en la búsqueda del desarrollo y de la integración.\n' +
			'El autor destaca especialmente la vigencia y validez de la filosofía de la historia propuesta por el E.L. para una adecuada interpretación del impacto del cambio técnico generado por el actual capitalismo cibernético que está transformando el mundo a una escala y velocidad sin precedentes.',
		state: null,
		topic: 'Historia económica de Latinoamérica',
		language: 'Español',
		source2: 'https://www.librospatagonia.com/library/publication/el-desarrollo-y-la-integracion-de-america-latina-una-odisea-inconclusa'
	}
]

export const blogPosts = [
	{
		id: '12938104823490',
		title: 'tesrt',
		content: 'aslfknasljkfna',
		author: 'holaaaaa',
		date: '23939328'
	},
	{
		id: '2938293849',
		title: 'test',
		content: 'aslfknasljkfna',
		author: 'holaaaaa',
		date: '232320924'
	}
]

export const PDF_files = [
	{
		id: '',
		link: '',
	}
]